# Generated by Django 5.1.2 on 2024-11-05 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_combo', models.CharField(max_length=100)),
                ('gia_combo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DinhDangPhim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dinh_dang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sdt', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nữ')], max_length=10)),
                ('ngay_sinh', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Phim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phim', models.CharField(max_length=200)),
                ('dao_dien', models.CharField(max_length=100)),
                ('dien_vien', models.TextField()),
                ('thoi_luong', models.PositiveIntegerField()),
                ('tom_tat', models.TextField()),
                ('thumbnail', models.CharField(max_length=200)),
                ('do_tuoi', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='RapChieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_rap', models.CharField(max_length=200)),
                ('dia_chi', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_the_loai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('noi_dung', models.TextField()),
                ('user_binh_luan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.nguoidung')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.phim')),
            ],
        ),
        migrations.CreateModel(
            name='GheNgoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ghe', models.CharField(max_length=10)),
                ('loai_ghe', models.CharField(max_length=50)),
                ('gia_ve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rap_chieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.rapchieu')),
            ],
        ),
        migrations.AddField(
            model_name='phim',
            name='the_loai',
            field=models.ManyToManyField(to='database.theloai'),
        ),
        migrations.CreateModel(
            name='XuatChieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_chieu', models.DateTimeField()),
                ('dinh_dang_phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.dinhdangphim')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.phim')),
                ('rap_chieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.rapchieu')),
            ],
        ),
        migrations.CreateModel(
            name='Ve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_ghe', models.CharField(blank=True, editable=False, max_length=50)),
                ('gia_ve', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('ma_qr_ve', models.CharField(max_length=100)),
                ('link_face', models.CharField(max_length=200)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.combo')),
                ('ghe_ngoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ghengoi')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.phim')),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.rapchieu')),
                ('user_mua_ve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.nguoidung')),
                ('thoi_gian_chieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.xuatchieu')),
            ],
        ),
    ]
